### ISSUE TITLE
This is a public hazard

### ISSUE THREAD

**Issue by JaniM** [VulnPlanet/l3x#3]
The program sends the entire source file for each regex match to GPT, which easily becomes extremely expensive. For example, a 1000 line Rust file can easily have 100 matches with normal usage, which'd lead to 100 000 lines of code sent, which can easily be a million tokens. GPT4 costs $10 / million tokens, so that's $10 to scan a fairly average file.

All of the integer overflow patterns can be particularly egregious and will make any mathy code rack up an extravagant bill.

Running this against rustc will produce 4600 matches just for the keyword `unsafe`. I don't even know how high the number of tokens sent goes here. Billions?

That's all without accounting for the fix suggestions GPT sends back. Those also cost a lot.

Don't run this, it will bankrupt you.

---
This rule is particularly fun, matching every `&mut`.
https://github.com/VulnPlanet/l3x/blob/3887ee556c29c6917907352eaa88d47f4b1fb94f/l3x/src/vulnerability_checks.rs#L57-L66

**Comment by ghost** [comment]
> Three different models are utilized: GPT-4, Gemini, and Claude 2.

Multiply that by three.

**Comment by ghost** [comment]
Taking the `&mut` regex *alone* being ran on Rustc, this will send approximately 158 million tokens to ChatGPT.

If we assumed that ChatGPT returned an approximate 1/3rd of the length of each input, **just** the `&mut` regex would cost around 8 thousand USD. Ignoring network costs.

8 grand for *one* regex. Out of the dozens this shit has.

**Comment by ghost** [comment]
# Input Tokens
- RUST001: 30 million
- RUST002: 30 million
- RUST003: 2.5 million
- RUST004: 17 **billion**
- RUST005: 158 million
- RUST006: 10 million
- RUST007: 300
- RUST008: doesn't exist, lol
- RUST009: 350 thousand
- RUST010: 30 million
- RUST011: 30 million
- RUST012: 11 million
- RUST013: 0
- RUST014: 30 million
- RUST015: 4 million
- RUST016: 3 million
- RUST017: 12 million
- RUST018: 500 thousand
- RUST019: 0
- RUST020: 4.5 **billion**

**Comment by ghost** [comment]
That comes to an approximate 21_851_350_300 input tokens
Input cost = 655,541 USD

Assuming the output of each request is at-least 1/2rd of the input, that totals to about **1.3 million dollars**.

These are **only** the first 20 lints and we're already in the million dollar range. Per. Invocation. :-)

**Comment by herabit** [comment]
This seems like a scalable and robust design. Very. Robust.

**Comment by herabit** [comment]
> The program sends the entire source file for each regex match to GPT, which easily becomes extremely expensive. For example, a 1000 line Rust file can easily have 100 matches with normal usage, which'd lead to 100 000 lines of code sent, which can easily be a million tokens. GPT4 costs $10 / million tokens, so that's $10 to scan a fairly average file.
> 
> All of the integer overflow patterns can be particularly egregious and will make any mathy code rack up an extravagant bill.
> 
> Running this against rustc will produce 4600 matches just for the keyword `unsafe`. I don't even know how high the number of tokens sent goes here. Billions?
> 
> That's all without accounting for the fix suggestions GPT sends back. Those also cost a lot.
> 
> Don't run this, it will bankrupt you.
> 
> This rule is particularly fun, matching every `&mut`.
> 
> https://github.com/VulnPlanet/l3x/blob/3887ee556c29c6917907352eaa88d47f4b1fb94f/l3x/src/vulnerability_checks.rs#L57-L66

Also it is worth mentioning that many of these patterns ***are not necessarily, remotely indications of insecure Rust code, most of them seem to apply to perfectly safe, and valid Rust code.***.

**Comment by kajojify** [comment]
Hello folks! 
Thank you for the interest in the project and thanks for the valuable feedback. 
It is worth mentioning that the project is just the concept, MVP, which is stated in the readme. So, it is only for testing purposes for the moment (putting this into the readme).

A few comments about the feedback:
1. The latest PR changes the approach, so we don't send the code along with every single pattern match anymore, but rather send the code with all matches at once. This should reduce the number of tokens and api calls pretty much. 
2. The only supported LLM is GPT-3.5 for the moment, which costs much less than GPT-4.
3. > Also it is worth mentioning that many of these patterns are not necessarily, remotely indications of insecure Rust code, most of them seem to apply to perfectly safe, and valid Rust code.. 

Yes, they are. Generally speaking, it is ok for static analyzer to have false positives, but we will improve rules to reduce them. 

We will keep improving things.
Thanks.
All the best.
