### ISSUE TITLE
Failed to get a valid response from OpenAI

### ISSUE THREAD

**Issue by chriscczhou** [VulnPlanet/l3x#5]
Use apikey can request  success : 
```curl https://api.openai.com/v1/models \
  -H "Authorization: Bearer $OPENAI_KEY" \
  -H "OpenAI-Organization: org-jzbvMiPRhVKpZWrIQ1JkhvOr"
```

But run error:
`Error: Custom { kind: Other, error: "Failed to get a valid response from OpenAI" }`

**Comment by kajojify** [comment]
Hey there! Sorry for a long response.
Fixed it in the latest commit. Now you can set up openai org and project via the corresponding env variables: `OPENAI_ORG_ID` and `OPENAI_ORG_ID`.
