### ISSUE TITLE
Failed to get a valid response from OpenAI

### ISSUE THREAD

**Issue by chriscczhou** [VulnPlanet/l3x#8]
Hey there! Sorry for a long response.
Fixed it in the latest commit. Now you can set up openai org and project via the corresponding env variables: `OPENAI_ORG_ID` and `OPENAI_ORG_ID`.

_Originally posted by @kajojify in https://github.com/VulnPlanet/l3x/issues/5#issuecomment-2090225813_
           
I'm set `OPENAI_API_KEY`,`OPENAI_ORG_ID` and `OPENAI_PROJECT_ID` , but still can't run l3x.
Use curl to request openapi  can success.

![image](https://github.com/VulnPlanet/l3x/assets/108380177/ce544dd8-2e5a-49a7-8bf4-9169c95a01d2)

**Comment by yevh** [comment]
Hey @chriscczhou really sorry for the late response. In the latest update we added support of GPT-4 and also `--no-validation` flag, could you please check if it works for you?
